project:
  type: website
editor:
  render-on-save: true
execute:
  freeze: auto # re-render only when source changes

website:
  page-navigation: true
  title: "AgReFed Data-Harvester"
  site-url: https://sydney-informatics-hub.github.io/AgReFed-Workshop
  repo-url: https://github.com/Sydney-Informatics-Hub/AgReFed-Workshop
  repo-actions: [issue]

  page-footer:
    right: "Site built with [Quarto](https://quarto.org/)."
    left: "&copy; Sydney Informatics Hub, 2022"

  navbar:
    title: "SIH-AgReFed Workshop"
    background: "#ff3333" # "#ff3333" "#424242"
    logo: "images/logo_white.png"
    pinned: false
    left:
      - text: "{{< fa house-chimney >}}"
        file: index.qmd
    right:
      - text: "{{< fa brands python >}} Python Workshop"
        file: pydocs/py00-workshop.qmd
      - text: "{{< fa brands r-project >}} Workshop"
        file: rdocs/r00-workshop.qmd

  sidebar:
    logo: "images/sih_logo.svg"
    pinned: true
    align: center
    tools:
      - icon: globe
        href: https://www.sydney.edu.au/research/facilities/sydney-informatics-hub.html
        text: "SIH Website"
      # - icon: github
      #   href: https://github.com/sydney-informatics-hub/agrefed-workshop
      #   text: "GitHub Repository"
    style: "floating" # "floating" "docked"
    search: false
    collapse-level: 1
    contents:
      - text: "Home"
        href: index.qmd
      - text: "About Us"
        href: about.qmd
      - text: "Code of Conduct"
        href: code-of-conduct.qmd
      - text: "YAML Overview"
        href: Settings_Overview.md
      # - text: "{{< fa link >}} `dataharvester`"
      #   href: https://sydney-informatics-hub.github.io/dataharvester/
      - text: "{{< fa circle-question >}} FAQ"
        href: faq.qmd

      # Python Workshop
      - text: "---"
      - section: "Python Workshop"
        contents:
          - text: Introduction
            href: pydocs/py00-workshop.qmd
          - section: "Setting up"
            contents:
              - text: "Python Environment"
                href: pydocs/setup-python
              - text: "Google Earth Engine"
                href: pydocs/setup-gee.qmd

          - text: "{{< fa hammer >}} 1: Intro and Basic Usage"
            href: pydocs/p10-basic.ipynb
          - text: "{{< fa hammer >}} 2: Advanced harvest configuration"
            href: pydocs/p20-advanced.ipynb
          - text: "{{< fa hammer >}} 3: Custom Workflows"
            href: pydocs/p30-technical.ipynb
          # - text: W3 Advanced
          #   href: pydocs/py04-advanced.qmd
          # - text: Data Harvester Notebook
          #   href: pydocs/Data_Harvest.ipynb

      # R Workshop
      - text: "---"
      # - text: "R Workshop"
      #   href: rdocs/r00-workshop.qmd
      - section: "R Workshop"
        contents:
          - text: "Introduction"
            href: rdocs/r00-workshop.qmd
          - section: "Setting up"
            contents:
              - text: "Google Earth Engine"
                href: rdocs/r03-google-earth-engine.qmd
              - text: "RStudio Cloud"
                href: rdocs/r01-setup-cloud.qmd
              - text: "RStudio Desktop"
                href: rdocs/r02-setup-desktop.qmd
          - text: "{{< fa life-ring >}} Troubleshooting"
            href: rdocs/r99-troubleshooting.qmd
          - text: "---"
          - text: "[{{< fa hammer >}} 1: Introduction"
            href: rdocs/r20-introduction.qmd
          - text: "{{< fa hammer >}} 2: Custom Workflows"
            href: rdocs/r30-basic.qmd
          - text: "{{< fa hammer >}} 3: Advanced Features"
            href: rdocs/r40-advanced.qmd

      # Additional links
      # - section: folder/example.qmd
      #   contents:
      #     - folder/rstudio.qmd
      #     - folder/jupyter.md
      # - href: another_example.qmd
      #   text: This will change text in sidebar

format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      # dark: [cosmo, theme-dark.scss]
    fontsize: 13pt
    code-copy: true
    code-overflow: wrap
    toc: true

filters:
  - include-files.lua
  - quarto
