---
title: Frequently Asked Questions
---

- [What is the AgReFed Data-Harvester?](#q-what-is-the-agrefed-data-harvester)
- [Who should attend these workshops?](#q-who-should-attend-these-workshops)
- [What are the pre-requisites?](#q-what-are-the-pre-requisites)
- [What is the cost of attending these workshops?](#q-what-is-the-cost-of-attending-these-workshops)
- [Why should I use the Data-Harvester over other tools?](#q-why-should-i-use-the-data-harvester-over-other-tools)
<!-- - [Can you provide a certificate of completion?](#q-can-you-provide-a-certificate-of-completion) -->

#### Q: What is the AgReFed Data-Harvester?
AgReFed is the [Agriculturual Research Federation](https://www.agrefed.org.au/). The Data-Harvester is a set of open-source tools, developed by AgReFed and SIH, written in Python but interfaced through Python or R. The tools make geo-spatial/remote-sensing data more easily accessible, and make the data download and processing steps seamlessley reproducible. The Data-Harvester combines multiple sources so a user does not need to manually visit each repository and figure out how to download the data they need.

#### Q: Who should attend these workshops?

Anyone who is interested in extracting data from satellite imagery and/or national datasets. Although the training material has a strong emphasis on agricultural research, the techniques should apply anywhere remote sensing or satellite data are needed such as in ecology, forestry, fisheries, and environmental monitoring.

#### Q: What are the pre-requisites? {#pre-requisites}

Knowlege of remote sensing and/or geospatial concepts is desired, but not required. The training material will cover the basics of obtaining data for research, and will only provide a gentle introduction to remote sensing concepts.

**If you are attending a Python Workshop**, you should have a basic understanding of Python and understand how to use a command line interface (e.g. Terminal on Mac or Linux, or Command Prompt on Windows). 

**If you are attending an R Workshop**, you should have a basic understanding of R and be comfortable with writing lines of code to perform actions. If you are not familiar with R, we recommend that you take a look at the [R for Data Science](https://r4ds.had.co.nz/) book. Before attending a workshop, you should also install the [RStudio IDE](https://www.rstudio.com/products/rstudio/download/) and the latest version of [R](https://cran.r-project.org/).


#### Q: What is the cost of attending these workshops?

These workshops are **free** to attend. However, we do ask that you register for the workshop so that we can plan accordingly. If you are unable to attend, please let us know so that we can open up your spot to someone else.


#### Q: Why should I use the Data-Harvester over other tools?

The Data-Harvester is a good starting point for those who are new to remote sensing and satellite data. It provides a simple interface to access data and perform basic analysis. Importantly, **users are not limited to the data and analysis provided by the Data-Harvester**. We have made sure that data objects are in accessible formats which can be easily exported for use in other packages. For example, users can use the Data-Harvester to access data from the [Google Earth Engine](https://earthengine.google.com/), and if they wish to perform additional transformations before exporting the data, they can export the Earth Engine object to the Earth Engine API in Python, or [`rgee`](https://r-spatial.github.io/rgee/) if using R. or, they may download data using other products, but use the Data-Harvester to perform pixel reduction or temporal aggregation.


#### Q: Is it safe to authenticate my Google account with the Data-Harvester?
Authentication is the process by which your identity is confirmed through the use of some kind of credential. When you use the Google Earth Engine (GEE) API, you are giving the Data-Harvester permission to access a **very specific portion** of your Google account - mainly a digital "notebook" that  allows you to access GEE. This is the same as if you were to use the GEE API directly. The Data-Harvester does not store any of your credentials, and you can revoke access to the Data-Harvester at any time.


<!-- #### Q: Can you provide a certificate of completion?

Yes, we can provide a certificate of completion for those who attend the workshop. Please let us know if you would like a certificate. -->
