---
title: "Data-Harvester Workshops"
subtitle: "Presented by Sydney Informatics Hub and the Agricultural Research Federation"
markdown:
    canonical: true
---


::: callout-tip
### Workshop information {.unnumbered}

The next AgReFed Geo-Data Harvester workshop will be run in **early 2023**. Please check back here for details.
<!-- <script src="https://cdn.logwork.com/widget/countdown.js"></script>
<a href="https://logwork.com/countdown-w5fs" class="countdown-timer" data-style="circles" data-timezone="Australia/Sydney" data-date="2022-11-03 13:30">Workshop starts in...</a> -->

:::

::: callout-note
### Python workshop {.unnumbered}
**Interested in a Data-Harvester workshop run in {{< fa brands python >}} Python? [Let us know](https://sydney.au1.qualtrics.com/jfe/form/SV_9TUKiEjaNEFPifk).** We'll be sending out an email to everyone who signed up for the course when it's ready to go.
:::

## About

Use the AgReFed Data-Harvester to **access, process and download** national (Australian) and global space/time data aimed at agricultural scientists, environmental scientists, ecologists and other researchers.

In the workshops, we will show you how to download and summarise geospatial data from a range of sources including:

<!-- 1. **Data retrieval:** access and download a diverse range of geospatial and soil data sources and APIs
2.  **Processing:** Spatial and temporal processing of data, which include image reduction/composition, access to satellite collections, cloud/shadow masking and calculation of spectral indices
3.  **Output:** export data in GeoTIFF or data frames which are ready for modelling workflows

Exercises will involve data retrieval from national/global datasets including: -->

-   [Soil and Landscape Grid of Australia (SLGA)](https://is.gd/i8nF0Z)
-   [SILO Climate Database](https://is.gd/ifJ8tB)
-   [Digital Elevation Model (DEM) of Australia](https://is.gd/ZLFwGs)
-   [Digital Earth Australia (DEA) Geoscience Earth Observations](https://is.gd/gRSlVG)
-   [GSKY Data Server for DEA Geoscience Earth Observations](https://is.gd/zFHxfD)
-   [Google Earth Engine](https://is.gd/VdO3Jx)

In addition, we will present some spatial and temporal aggregation, visualisation, and simple summary techniques.

<!-- Workshops are presented by the [**Sydney Informatics
Hub**](https://www.sydney.edu.au/research/facilities/sydney-informatics-hub.html)
in collaboration with the [**Agricultural Research
Federation**](https://www.agrefed.org.au/AgReFedPlatform).  -->
 
For more information about the workshops, including who these workshops are made for, check the [FAQ](/faq.qmd).

## Trainers

-   **Januar Harianto** (R Workshop Trainer)
-   **Nathaniel Butterworth** (Python Workshop Trainer)
-   *Sebastian Haan* (support)
-   *Henry Lydecker* (support)
-   *Eden Zhang* (support)
-   *Darya Vanichkina* (support)
-   *Thomas Bishop* (support)

