---
title: "R Workshop"
---

**The AgReFed Data-Harvester can be run in Python or R. **

This R workshop is aimed at people who are already familiar with R and RStudio. If you prefer to use Python, see the [Python Workshop](/pydocs/py00-workshop.qmd) for details.

::: callout-important
**Please read the [Code of Conduct](/code-of-conduct.qmd), [FAQ](/faq.qmd), and [Setting up](/rdocs/r01-setup.qmd) before joining the workshop.**
:::

## How to follow the sessions


### [{{< fa person-chalkboard >}} Demo]{style="color: green;"}

When you see this icon [{{< fa person-chalkboard >}}]{style="color: green;"}, the content will be demonstrated to you by the instructor. You should follow along and run the code in your own environment as you go.


### [{{< fa keyboard >}} Exercises]{style="color: blue;"}

Throughout the workshop, you will be asked to complete some exercises. These will be marked with this icon [{{< fa keyboard >}}]{style="color: blue;"}. These tasks are designed to help you practice what you have learned. They should take no more than 5 minutes each.


## Join us

::: callout-tip
### Workshop information {.unnumbered}

The next AgReFed Data-Harvester Workshop **in R** will be run on **Tue, 25 Oct, 2022, at 09:30am AEST (Sydney)**.

<script src="https://cdn.logwork.com/widget/countdown.js"></script>
<a href="https://logwork.com/countdown-w5fs" class="countdown-timer" data-style="circles" data-timezone="Australia/Sydney" data-date="2022-10-25 09:30">Workshop starts in...</a>

{{< fa comment >}} **Note**: The above workshop is open to staff and students of The University of Sydney only. The next workshop, also **in R**, can be registered by anyone and is now [open for registration](https://www.eventbrite.com.au/e/agrefed-data-harvester-workshop-tickets-425515517367). This workshop will be run on Thu, 03 Nov, 2022, at 01:30pm AEST (Sydney).
:::


- {{< fa chalkboard-user >}} **Zoom link**: [Register online](https://www.eventbrite.com.au/e/agrefed-data-harvester-workshop-tickets-425515517367r) and link to the workshop will be sent, via email, closer to the workshop date.
- {{< fa download >}} **Workshop material**: Click [here]() to download the workshop material. (*Link will be available closer to the workshop date.*)
