---
title: "{{< fa brands r-project >}}  Advanced features"
markdown:
    canonical: true
---

:::{.callout-tip}
## In this session

- Exploring other datasets in Earth Engine (5 min)
- Downloading large images from Google Earth Engine (5 min)
- Temporal Aggregation (10 min)
- Sampling point data from rasters (10 min)
- Exercise: Revisiting the YAML for sampling
- Exercise: Sampling point data from rasters
:::

## Available datasets in Earth Engine

Under construction.

- Discuss Landsat, Sentinel, MODIS supporting cloud masking and spectral indices
- Discuss use of other datasets, but with reduced functionality
- Attribute Python packages eemont for cloud masking and spectral indices functionality, geemap for mapping, geedim for large image downloads
- Run examples (show swapping of datasets, and locations outside of Australia)

## Aggregating raster data

Under construction.

- Discuss how to aggregate raster data
- Explore temporal aggregation using the `aggregate_temporal()` function
- Run examples
- Optional: discuss upcoming `aggregate()` method in GEE

## Sampling point data from rasters

Under construction.

- Talk about how to sample point data from rasters based on available point dataset using
    - `raster_query()`
    - YAML config
- Run examples
