colname_lat: Lat
colname_lng: Long
infile: ../testdata/Pointdata_Llara.csv
outpath: ../dataresults_testnotebook/
target_bbox: ''
target_dates: !!python/tuple
- 2021
target_res: 12.0
target_sources:
  DEA:
  - landsat_barest_earth
  - s2_barest_earth
  DEM:
  - DEM
  - Slope
  - Aspect
  Landscape:
  - Relief_300m
  Radiometric:
  - radmap2019_grid_dose_terr_filtered_awags_rad_2019
  SILO:
    monthly_rain:
    - Total
  SLGA:
    Bulk_Density:
    - 0-5cm
temp_res: 365
