---
title: Python Workshop
---
**The AgReFed Geoata-Harvester can be run in Python or R. **

This Python workshop is aimed at people who are more familiar with Python. If you prefer to use R, see the [R Workshop](/rdocs/r00-workshop.qmd) for details.

::: callout-important
## Pre-Workshop Setup
Please sign up for **Google Earth Engine** before the workshop. See [the GEE setup pages](/pydocs/setup-gee) for instructions.
:::

-- **Join our hosted virtual Python environment by clicking the button below and signing in with AAF**:

[AgReFed Python Workshop](https://jupyterhub.rc.nectar.org.au/){target="_blank"}

We will be following along these notes navigable in the left hand menu. Get started by [setting up Google Earth Engine](/pydocs/setup-gee) and [get a working Python Environemnt](/pydocs/setup-python). Then launch into the sessions with [1-Intro and Basic Usage](/pydocs/p10-basic).

## How to follow the sessions


### [{{< fa person-chalkboard >}} Demo]{style="color: green;"}

When you see this icon [{{< fa person-chalkboard >}}]{style="color: green;"}, the content will be demonstrated to you by the instructor. You should follow along and run the code in your own environment as you go.


### [{{< fa keyboard >}} Exercises]{style="color: blue;"}

Throughout the workshop, you will be asked to complete some exercises. These will be marked with this icon [{{< fa keyboard >}}]{style="color: blue;"}. These tasks are designed to help you practice what you have learned. They should take no more than 5 minutes each.


## Join us


::: callout-important
**We expect our participants to adhere to our [Code of Conduct](/code-of-conduct.qmd).
See the [FAQ](/faq.qmd) for more details or contact us at sih.training@sydney.edu.au**
:::

## Feedback

Please help us to continue providing great service to you, [complete the feedback survey before you go!](https://redcap.sydney.edu.au/surveys/?s=FJ33MYNCRR&training=56&training_date=2023-02-02)



