#####################################################
#                                                   #
#              Settings Data-Harvester              #
#                                                   #
# This is the settings file for the notebook.       #
# For more information on the available Data source #
# and layers, see README and Data_Overview.md       # 
#####################################################

##### Input and Output Specifications #####

# Input File:
infile: ../testdata/Pointdata_Llara.csv
# Output Path:
outpath: ../../dataresults/
# Headername of Latitude in input file:
colname_lat: Lat
# Headername of Longitude in input file:
colname_lng: Long

##### Settings for Spatial and Temporal Specifications #####

# Bounding Box as [lng_min, lat_min, lng_max, lat_max]:
# if None provided, bounding box will be inferred from input coordinates
target_bbox: ''
# Select years:
target_dates:
- 2021
# Spatial Resolution [arcsec]:
target_res: 6.0

##### Data Selection #####

target_sources:
  # Satellite data from Digital Earth Australia (DEA) Geoscience Earth Observations
  DEA:
  - landsat_barest_earth

  # National Digital Elevation Model (DEM) 1 Second
  DEM:
  - DEM
  
  # Landscape from SLGA
  Landscape:
  - Slope
  - Aspect
  - Relief_300m

  # Radiometric Data
  Radiometric:
  - radmap2019_grid_dose_terr_awags_rad_2019
  - radmap2019_grid_dose_terr_filtered_awags_rad_2019

  # SILO Climate Database
  # options for aggregation: 'mean', 'median', 'sum', 'std', 'perc95', 'perc5', 'max', 'min'
  SILO:
    max_temp:
    - median
    min_temp:
    - median
    monthly_rain:
    - sum


  # Soil data from Soil and Landscape Grid of Australia (SLGA)
  # Depth options: 0-5cm, 5-15cm, 15-30cm, 30-60cm, 60-100cm, 100-200cm
  SLGA:
    Bulk_Density:
    - 0-5cm
    Clay:
    - 0-5cm


  # Satellite data layers from Google Earth Engine (GEE)
  GEE:
  # grouped by methods preprocess(), aggregate() and download()
    preprocess:
      # collection as defined in the Earth Engine Catalog
      collection: LANDSAT/LC09/C02/T1_L2
      # if supplied, will use 'buffer' and 'bound'. else, will use bbox above
      coords: [149.769345, -30.335861]
      # If date range is supplied, will use below. Else, will use `target_dates`
      date: 2021-01-01
      end_date: 2021-12-31
      # circular buffer in metres
      buffer: null
      # convert buffer into square bounding box instead
      bound: null
      mask_clouds: True
      # if null, will download all available images. Else, will reduce to single
      # composite image based on summary stat provided
      reduce: median
      # spectral indices to calculate via Awesome Spectral Indices site
      spectral:
        - NDVI
        - NDWI
    aggregate:
      
      frequency: year # group data by period. Available: year, month, week
      method: mean    # summarise group by method
    download:
      bands: 
        - NDVI
        - SR_B2
        - SR_B3
        - SR_B4
      scale: 100   # in metres
      format: tif  # available: tif, png
